name: SkyWars
main: ak.CookLoco.SkyWars.SkyWars
version: 1.3
author: CookLoco
softdepend: [HolographicDisplays]
commands:
    sw:
        description: admin command.
        usage: /<command>
    leave:
        description: leave command.
        usage: /<command>
        aliases: [salir]
permissions:
    skywars.admin:
        description: Access for admin commands
        default: op
    skywars.user:
        description: Access for user features
        default: true